ShelterBST: main.o ShelterBST.o
	g++ -o ShelterBST main.o ShelterBST.o

main.o: main.cpp ShelterBST.h
	g++ -c -Wall -Werror -pedantic -std=c++11 main.cpp

ShelterBST.o: ShelterBST.cpp ShelterBST.h
	g++ -c -Wall -Werror -pedantic -std=c++11 ShelterBST.cpp
